automation:
  - id: 'spa error notify'
    alias: spa error warning
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.spa_error
      above: '0'
    condition: []
    action:
    - service: notify.notify
      data:
        message: Pump error {{ trigger.state }}
    mode: single
