## Creates a sensor (sensor.layzspa_display) that contains the values from the display on the pump.
## To achieve this, a helper sensor for the display's ASCII value is also created.

sensor:
  - platform: mqtt
    name: Layzspa Display ASCII
    unique_id: sensor.layzspa_display_ascii
    icon: mdi:segment
    state_topic: "layzspa/message"
    value_template: "{{ value_json.CH1 }},{{ value_json.CH2 }},{{ value_json.CH3 }}"
    expire_after: 700
    
template:
  - sensor:
      - name: Layzspa Display
        unique_id: sensor.layzspa_display
        state: >
          {% set ch1 = states('sensor.layzspa_display_ascii').split(',')[0] %}
          {% set ch2 = states('sensor.layzspa_display_ascii').split(',')[1] %}
          {% set ch3 = states('sensor.layzspa_display_ascii').split(',')[2] %}
          {% set charactermap =  {
          '32' : ' ', '45' : '-', '48' : '0', '49' : '1', '50' : '2',
          '51' : '3', '52' : '4', '53' : '5', '54' : '6', '55' : '7',
          '56' : '8', '57' : '9', '97' : 'a', '98' : 'b', '99' : 'c',
          '100' : 'd', '101' : 'e', '102' : 'f', '103' : 'g', '104' : 'h',
          '105' : 'i', '106' : 'j', '107' : 'k', '108' : 'l', '109' : 'm',
          '110' : 'n', '111' : 'o', '112' : 'p', '113' : 'q', '114' : 'r',
          '115' : 's', '116' : 't', '117' : 'u', '118' : 'v', '119' : 'w',
          '120' : 'x', '121' : 'y', '122' : 'z'} %}
          {{ charactermap[ch1]~charactermap[ch2]~charactermap[ch3] }}
